# Generated by Django 2.0.6 on 2018-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_van_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Security',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
