# Generated by Django 2.0.6 on 2018-06-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tj_van_app', '0002_auto_20180626_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Security',
        ),
    ]
