# Generated by Django 2.0.6 on 2018-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_van_app', '0003_remove_vehicle_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='secure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
