# Generated by Django 2.0.6 on 2018-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_van_app', '0004_vehicle_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_secure',
            field=models.BooleanField(default=False),
        ),
    ]
