# Generated by Django 2.0.6 on 2018-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_van_app', '0006_auto_20180626_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='d_dept_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
